########## SERVICES ##########
services:
#### Pong Game ####
  pong-game:
    container_name: pong-game
    build: .
    image: pong-game-img
    restart: always
    ports:
      - 4000:4000
    networks:
      - my-network

########## NETWORK ##########
networks: 
  my-network:
    driver: bridge